# Changing Index into One-Hot Encoding with Pytorch

In this post we cover how to use [torch.nn.functional](https://pytorch.org/docs/stable/nn.functional.html) to encode a integer label (eg 1,4,6) into a on-hot tensor (eg. [0,1,0,0,0])

## Why Use One-Hot Encoder

In many classification tasks the use of [one-hot encoding](https://en.wikipedia.org/wiki/One-hot) of labels is needed by some loss functions, this is especially true when there is more than 2 classes.

The benefit of one-hot encoding is that the neural network can have an output neuron for each class, when a [Softmax](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html) is applied just before the output results in an output tensor where all values add up to 1.0 and this is often read as likelihood.

## Example
An example could be classes <i>cat</i>, <i>dog</i>, <i>cow</i> and a photo of a <i>cow</i> might result in an output tensor that looks like this [.05, 0.5, .90] therefore we might describe this as having 5% likelihood of being <i>cat</i> or <i>dog</i> and 90% of being a <i>cow</i>.

The ground truth tensor for this case might look like [0, 0, 1] and the tensor of the difference between the predictions and ground truth could be described as [.05, .05, .1]

## Reproducing 
This code was created and tested using [Environment E037](https://github.com/kierenAW/conda_environments_for_data_science)

## Imports

We will only need torch to be imported for this example

In [1]:
import torch

## Example function

We use torch’s random function to create a tensor of the chosen length while randomly setting the class to the selected number indexing from zero.

In [2]:
def one_hot_encode_demo(num_classes = 2, idx_len = 10):
    
    print('Randomly generating index.....\n')
    idx = torch.Tensor(idx_len).random_(0, num_classes)
    
    print('The index is now', idx)
    
    print('\nCreating one-hot encoded tensor....')
    one_hot = torch.nn.functional.one_hot(idx.to(torch.int64), num_classes)
    
    print('\nThe one-hot encoded index is now:')
    print(one_hot)

## Display Some Examples

Now we create a very simple example with 2 classes to demonstrate the basic concept 

In [3]:
one_hot_encode_demo(num_classes = 2)

Randomly generating index.....

The index is now tensor([0., 1., 1., 0., 0., 0., 0., 1., 0., 0.])

Creating one-hot encoded tensor....

The one-hot encoded index is now:
tensor([[1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0]])


Now we create a more complex example with 10 classes

In [4]:
one_hot_encode_demo(num_classes = 10)

Randomly generating index.....

The index is now tensor([9., 9., 9., 8., 4., 8., 2., 3., 3., 5.])

Creating one-hot encoded tensor....

The one-hot encoded index is now:
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])


As a final example we create a tensor of 3 classes and a length of 25

In [5]:
one_hot_encode_demo(num_classes = 3, idx_len = 25)

Randomly generating index.....

The index is now tensor([1., 0., 0., 1., 0., 1., 2., 2., 2., 0., 1., 1., 1., 2., 2., 1., 2., 0.,
        0., 1., 0., 2., 2., 0., 0.])

Creating one-hot encoded tensor....

The one-hot encoded index is now:
tensor([[0, 1, 0],
        [1, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 0]])
